group 'com.iaphub.iaphub_flutter'
version '2.2.0'

def safeExtGet(String prop, Object fallback) {
    return rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

def kotlinVersion = safeExtGet('kotlin_version', '2.1.0')

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    namespace 'com.iaphub.iaphub_flutter'
    compileSdk safeExtGet('compileSdkVersion', 34)

    compileOptions {
        sourceCompatibility safeExtGet('sourceCompatibility', JavaVersion.VERSION_1_8)
        targetCompatibility safeExtGet('targetCompatibility', JavaVersion.VERSION_1_8)
    }

    kotlinOptions {
        jvmTarget = safeExtGet('jvmTarget', '1.8')
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdk safeExtGet('minSdkVersion', 19)
    }
}

dependencies {
    implementation 'com.iaphub:iaphub-android-sdk:5.2.1'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"
    implementation 'com.google.code.gson:gson:2.8.9'
}
